version: 2
jobs:
  test_coco_assistant:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install Cython numpy==1.16.0
            pip install -r requirements.txt
            pip install pytest
            make remove && make clean
            cd tests
            py.test -vv tests.py
workflows:
  version: 2
  test-all:
    jobs:
      - test_coco_assistant